spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop
    username: root
    password: noah_1@23.Djanor
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      keepalive-time: 30000
      max-lifetime: 1800000
      idle-timeout: 600000

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
